### ISSUE TITLE
Add build support for Newer Asuswrt-Merlin Supported routers

### ISSUE THREAD

**Issue by jumpsmm7** [Adamm00/amcfwm#1]
RMerlin has added support for several new Router models. Is there away you can add build support for the newer supported models? 

Current List of supported Models =
Older platform:

    RT-AC66U_B1 (same firmware as the RT-AC68U)
    RT-AC68U (including revisions C1 and E1)
    RT-AC68P (same firmware as RT-AC68U)
    RT-AC68UF (same firmware as RT-AC68U)
    RT-AC68U V3 (same firmware as RT-AC68U)
    RT-AC1900 (same firmware as RT-AC68U)
    RT-AC1900P (same firmware as RT-AC68U)
    RT-AC88U
    RT-AC3100
    RT-AC5300

HND platform:

    RT-AC86U
    RT-AC2900 (same firmware as RT-AC86U)
    GT-AC2900
    RT-AX88U
    GT-AX11000
    RT-AX56U
    RT-AX58U
    RT-AX3000 (same firmware as RT-AX58U)
    RT-AX86U
    RT-AX68U

**Comment by Adamm00** [comment]
Been very busy the past few months, will add support for the newer models when time persists.

**Comment by vladut123** [comment]
> Been very busy the past few months, will add support for the newer models when time persists or permits?

**Comment by vladut123** [comment]
Adamm00 please update this script there are more than 5 months and no update to this script why?

**Comment by ptr1337** [comment]
> Adamm00 please update this script there are more than 5 months and no update to this script why?

Needs to be expanded for more Firmware's Support. 

I have just created a Docker Image, which automatically got all needed dependencies.
You can run after pulling and running the container the ac86u.sh script which pulls the GitHub Repo's for the Toolchains and the firmware and set up the toolchains.

Only tested right now for the AC86U and is running fine.

GitHub Repo with more Instructions: 

https://github.com/ptr1337/asus-merlin-wrt-docker-builder

DockerHub:

https://hub.docker.com/r/pttrr/asus-merlin-wrt-builder

Feel free to create a issue or a PR.

**Comment by jumpsmm7** [comment]
> 
> 
> > Adamm00 please update this script there are more than 5 months and no update to this script why?
> 
> Needs to be expanded for more Firmware's Support.
> 
> I have just created a Docker Image, which automatically got all needed dependencies.
> You can run after pulling and running the container the ac86u.sh script which pulls the GitHub Repo's for the Toolchains and the firmware and set up the toolchains.
> 
> Only tested right now for the AC86U and is running fine.
> 
> GitHub Repo with more Instructions:
> 
> https://github.com/ptr1337/asus-merlin-wrt-docker-builder
> 
> DockerHub:
> 
> https://hub.docker.com/r/pttrr/asus-merlin-wrt-builder
> 
> Feel free to create a issue or a PR.

Not to knock the wind off your Docker, but this was originally designed for setup with VM. I do not imagine the user base will quickly convert over to Docker. Don't get me wrong, Docker is great.

**Comment by ptr1337** [comment]
Its just a example project for building it into Docker since i dont use any VM's or Windows.
So just for me a solution a perfect solution for several devices.

**Comment by jumpsmm7** [comment]
@Adamm00 I know you are busy. I hope everything is going well for you. I also hope at some point you do get a chance to update this to support the current platforms. I appreciate your hard work, creativeness, and long term efforts.

**Comment by ptr1337** [comment]
> @Adamm00 I know you are busy. I hope everything is going well for you. I also hope at some point you do get a chance to update this to support the current platforms. I appreciate your hard work, creativeness, and long term efforts.

And again, its not hard to install docker (windows, linux, macos), clone my files and docker-compose up -d and run the script.

**Comment by jumpsmm7** [comment]
> > @Adamm00 I know you are busy. I hope everything is going well for you. I also hope at some point you do get a chance to update this to support the current platforms. I appreciate your hard work, creativeness, and long term efforts.
> 
> And again, its not hard to install docker (windows, linux, macos), clone my files and docker-compose up -d and run the script.

sorry I am not looking for a docker solution.

**Comment by ptr1337** [comment]
Then dont cry here and develop your own stuff. 

Its mostly 3 commands you need to run. congrats

**Comment by jumpsmm7** [comment]
> Then dont cry here and develop your own stuff.
> 
> Its mostly 3 commands you need to run. congrats

No one is crying they just are not looking for your solution, please find another place to troll.

**Comment by Adamm00** [comment]
I have added support for the GT-AC2900, GT-AX11000 and RT-AX68U in https://github.com/Adamm00/amcfwm/commit/37ebd67f5b242bb3c4f0acab5c7286dcd0f8ba4e

fwiw; This script is modular and adding support is mostly a copy and paste job, anyone can create pull requests, use this commit for future reference. 

My free time is almost non-existent and my motivation even lower due to a combination of how Tim @ SNB neutered the community and Merlin being the gatekeeper of who is "allowed" to build with TM components effectively making this script useless for anyone wanting to use AiProtect or QOS.

It's quite an unfortunate situation what happened to the community and the lack of creativity and new scripts in the last year speaks volumes, but I digress.
