### ISSUE TITLE
Base amng repo dir is never updated

### ISSUE THREAD

**Issue by dave14305** [Adamm00/amcfwm#14]
Only the individual model trees get updated during `clean_tree()` after being rsynced from the `amng` directory. `amng` and remote origin will diverge as time goes on. `clean_tree()` will revert to that point in time, then checkout and pull again in each model directory.

The `build` command should probably `git pull` inside `$HOME/amng` before running `clean_tree()`. Unless there’s a use for keeping it static.

**Comment by Adamm00** [comment]
No particular reason for this. I was just copying the original implementation at the time (or perhaps I made an error, who knows).

**Comment by dave14305** [comment]
I think Merlin’s use is fine when his base repo is actively committed to. For amcfwm, it probably needs to be updated before syncing.

Other ideas/to-dos:
- use `--depth 1` for initial git clones to reduce time/size
- Add option to build sequentially instead of in parallel
- Disabling `rsync tree` breaks building because model directories don’t get created
- amcfwm.cfg can end up with empty file or empty values during initial setup. Needs investigating still.
- A failed build won’t rerun without deleting the .git file, since the git hash hasn’t changed

**Comment by Adamm00** [comment]
I don't know if the current package list creates a working Ubuntu 20.04 build either. Will run some test builds now

>  A failed build won’t rerun without deleting the .git file, since the git hash hasn’t changed

This was an intended feature (and can be disabled via force build setting), this is to prevent a build server like mine from repeatedly compiling when there is an issue with the repo.
