### ISSUE TITLE
Current package list doesn't produce a working build on Ubuntu 20.04

### ISSUE THREAD

**Issue by Adamm00** [Adamm00/amcfwm#17]
[rt-ax88u-output.txt](https://github.com/Adamm00/amcfwm/files/10813061/rt-ax88u-output.txt)
[gt-ax6000-output.txt](https://github.com/Adamm00/amcfwm/files/10813063/gt-ax6000-output.txt)
[rt-ax86u-output.txt](https://github.com/Adamm00/amcfwm/files/10813064/rt-ax86u-output.txt)

**Comment by kernol51** [comment]
Until the Merlin Maestro made structural changes to the Master - I was able to build with your script.
That is blown once again - at least for RT-AC86U!
I guess we will have to wait for the Repo to settle?

**Comment by Adamm00** [comment]
Looks like things finally settled. As far as I can reproduce amcfwm should confidently be able to set up a working build env
