### ISSUE TITLE
Compiling now seems broken ??

### ISSUE THREAD

**Issue by kernol51** [Adamm00/amcfwm#3]
I fully appreciate that you are hectically busy - and remain less inclined to support this script given the treatment meted out to you and other add-on builders ... so forgive me for appealing to you to take a look at a compile for the AX86U using this script.

The compile runs almost to the end as far as I can make out - then fails - here are the messages on the terminal screen ...
--- 06:52 - Global cleanup...
--- 06:52 - Preparing trees

*** 06:52 - Cleaning up rt-ax86u...
*** 06:52 - Updating rt-ax86u tree...
*** 06:59 - rt-ax86u code ready.

--- 06:59 - All trees ready!

--- 06:59 - Launching all builds
*** 06:59 - Starting building rt-ax86u...
--- 06:59 - All builds launched, please wait...

!!! 07:45 - rt-ax86u build failed! (00h:52m:31s)
!!! 07:45 - /home/johnw/amcfwm/rt-ax86u-output.txt

=== 07:45 - All done!

The last successful compile I did using the script was for 386.3-Alpha_1. 
Since then I spotted your update adding further models [none of interest to me] and applied it before attempting to compile.
I also reran option 2 to update the VM as well as option 3 - toolchain update [having updated Ubuntu 18.04].
First attempt failed.
I have fully uninstalled the script - and then re-installed from scratch.
Attempt this morning also failed.

The rt-ax86u-output.txt file is almost 20Mb - so hesitate to attach - but can if it will help.
Noteworthy warnings at the end of the file are ...

make -C tor -j4
make[5]: Entering directory '/home/johnw/amng.ax86/release/src/router/tor'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/johnw/amng.ax86/release/src/router/tor/missing aclocal-1.16 -I m4
/home/johnw/amng.ax86/release/src/router/tor/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:7379: recipe for target 'aclocal.m4' failed
make[5]: *** [aclocal.m4] Error 127
make[5]: Leaving directory '/home/johnw/amng.ax86/release/src/router/tor'
Makefile:4697: recipe for target 'tor' failed
make[4]: *** [tor] Error 2
make[4]: Leaving directory '/home/johnw/amng.ax86/release/src/router'
Makefile:31: recipe for target 'router_all' failed
make[3]: *** [router_all] Error 2
make[3]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x/userspace'
build/Makefile:307: recipe for target 'userspace' failed
make[2]: *** [userspace] Error 2
make[2]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x'
Makefile:5174: recipe for target 'bin' failed
make[1]: *** [bin] Error 2
make[1]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x'
Makefile:5370: recipe for target 'rt-ax86u' failed
make: *** [rt-ax86u] Error 2

If you can help - GREAT ... if not ... I will understand and not bother you again.

**Comment by alexins** [comment]
If you are using "Ubuntu 18.04" then you need to apply this patch:
[fix_Ubuntu 18.04.zip](https://github.com/Adamm00/amcfwm/files/6836623/fix_Ubuntu.18.04.zip)

**Comment by kernol51** [comment]
Sorry @alexins - but I have no idea who you are or what you may have included in your .zip file ... so ZERO chance of me downloading or applying any such.  I will wait patiently for a response from the author of this script.

**Comment by Adamm00** [comment]
Try;

sudo apt-get update
sudo apt-get install automake-1.16

**Comment by alexins** [comment]
The problem is you don't have "aclocal-1.16". You need to re-generate the build-scripts for "aclocal-1.15".
Here "link to code from Adamm00 #625a62fd [https://github.com/Adamm00/amcfwm/commit/625a62fd942c074ae157f44ad3eac7f3bdb4b5eb?branch=625a62fd942c074ae157f44ad3eac7f3bdb4b5eb&diff=split](url) " you can see how you can do it.
In this patch, you need to change the line: "if grep -qF "Ubuntu 20.04" "/etc/os-release"; then" 
like this: "if grep -qF "Ubuntu 18.04" "/etc/os-release"; then"

Or you can install "Ubuntu 20.04". After installing "Ubuntu 20.04" do this: "sudo dpkg-reconfigure dash" -> "Then tell it to NOT use dash"
and then follow the installation instruction "amcfwm"
There are no build issues in "Ubuntu 20.04"!

**Comment by alexins** [comment]
> Try;
> 
> sudo apt-get update
> sudo apt-get install automake-1.16

This does not work with "Ubuntu 18.04"

```
alex@ubuntu:~$ sudo apt-get update
Hit:1 http://archive.canonical.com/ubuntu bionic InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu bionic InRelease                                               
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease       
Hit:4 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease      
Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done                      
alex@ubuntu:~$ sudo apt-get install automake-1.16
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package automake-1.16
E: Couldn't find any package by glob 'automake-1.16'
E: Couldn't find any package by regex 'automake-1.16'
```

**Comment by kernol51** [comment]
Many thanks @alexins and @Adamm00 - I understood this script was originally built for 18.04 and did not realise it was now better suited to 20.04.
I am simply upgrading my VM to 20.04 and will then try fresh install of the script.

**Comment by alexins** [comment]
@kernol51 , After installing "Ubuntu 20.04" do this: "**sudo dpkg-reconfigure dash**" -> "**Then tell it to NOT use dash**"

**Comment by kernol51** [comment]
Thanks again - done clean install - just running apt-get update etc and will then follow your advice before clean install of @Adamm00 's script.  It would be help if he changed the links on his first page to 20.04 downloads rather than the 18.04 ones ;-)

**Comment by kernol51** [comment]
That's strange - this time the compile failed due to not having aclocal-1.**15** 
Wasted 40 minutes before the compile failed with this error ...

make -C wget -j4
make[5]: Entering directory '/home/johnw/amng.ax86/release/src/router/wget'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/johnw/amng.ax86/release/src/router/wget/build-aux/missing aclocal-1.15 -I m4
/home/johnw/amng.ax86/release/src/router/wget/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make[5]: *** [Makefile:1506: aclocal.m4] Error 127
make[5]: Leaving directory '/home/johnw/amng.ax86/release/src/router/wget'
make[4]: *** [Makefile:7181: wget] Error 2
make[4]: Leaving directory '/home/johnw/amng.ax86/release/src/router'
make[3]: *** [Makefile:31: router_all] Error 2
make[3]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x/userspace'
make[2]: *** [build/Makefile:308: userspace] Error 2
make[2]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x'
make[1]: *** [Makefile:5186: bin] Error 2
make[1]: Leaving directory '/home/johnw/amng.ax86/release/src-rt-5.02p1axhnd.675x'
make: *** [Makefile:5374: rt-ax86u] Error 2

I have run sudo apt-get install automake-1.15 and will see if this time a compile will work ... ???

**Comment by alexins** [comment]
I did a test of the last code change. Clean install "Ubuntu 20.04".
Building the code doesn't work:
```
/home/alex/amng.ax68/release/src/router/wget/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
```

To build the code correctly, the system must have two versions of "automake" installed: "automake-1.15" and "automake-1.16"
For the build to work with "Ubuntu 20.04" you need to undo the change associated with "automake-1.16". On "Ubuntu 20.04" "automake-1.16" is installed by default, requires "automake-1.15" to be installed.

To make the code work with "Ubuntu 18.04", the changes to "aclocal-1.16" must be removed. 
And you need to add a patch:
```
if grep -qF "Ubuntu 18.04" "/etc/os-release"; then
echo "*** $(date +%R) - Patching wget"
cd "$HOME/$FWPATH/../src/router/wget" || exit 1
autoreconf -f -i >/dev/null 2>&1
echo "*** $(date +%R) - Patching tor"
cd "$HOME/$FWPATH/../src/router/tor" || exit 1
autoreconf -f -i >/dev/null 2>&1
```

**Comment by alexins** [comment]
> I have run sudo apt-get install automake-1.15 and will see if this time a compile will work ... ???

Yes, that's right, you need to do this:

```
sudo apt-get update
sudo apt-get install automake-1.15
```

**Comment by kernol51** [comment]
> > I have run sudo apt-get install automake-1.15 and will see if this time a compile will work ... ???
> 
> Yes, that's right, you need to do this:
> 
> ```
> sudo apt-get update
> sudo apt-get install automake-1.15
> ```

Exactly what I did - and after that I got a successful build - MANY thanks for your input ... and pleased you did not take offence at my caution when you posted .zip files as a solution ;-)

**Comment by alexins** [comment]
> Exactly what I did - and after that I got a successful build

It's a good news!
After installing "automake-1.15" my second test was successful!

![2021-07-19 165538](https://user-images.githubusercontent.com/30778238/126187529-07ef322b-91c8-4fa8-a910-71fdd73f646d.png)



> and pleased you did not take offence at my caution when you posted .zip files as a solution ;-)

I'm used to it and don't really pay attention to things like that)

**Comment by kernol51** [comment]
Many thanks @Adamm00 and @alexins - all sorted.
