### ISSUE TITLE
self compile broken again - bad Master

### ISSUE THREAD

**Issue by kernol51** [Adamm00/amcfwm#5]
Not really your issue ... but the Merlin Master is messed up again and compiles fail.
Two things for you to consider when you have time ...
1 - add the extra router models that are now being supported;
2 - add a script that checks that the Master has what is needed for compiles to work?
Your call - I fully enjoy your script ... but understand if its no longer worth your while supporting.

**Comment by Adamm00** [comment]
Will devote some time here in the near future, just received a shiny new GT-AX6000 for development.

https://i.imgur.com/BTQgpCv.png

**Comment by kernol51** [comment]
Impressive stats - enjoy :-)

**Comment by vladut123** [comment]
> Will devote some time here in the near future, just received a shiny new GT-AX6000 for development.
> 
> https://i.imgur.com/BTQgpCv.png

In like 3 weeks to one month?

**Comment by kernol51** [comment]
> > Will devote some time here in the near future, just received a shiny new GT-AX6000 for development.
> > https://i.imgur.com/BTQgpCv.png
> 
> In like 3 weeks to one month?

There is absolutely no rush ... several models are not included in the Master at present ... notably the RT-AX86U [which is my main router] ... so until the next release version of the firmware - 386.7 - no point in sorting any amcfwn script issues.

It also seems that Merlin is now compiling under Ubuntu 22 - and so any script issues for that version may have to be resolved too.

**Comment by jumpsmm7** [comment]
@kernol51 

If you have time and can follow the commit here https://github.com/Adamm00/amcfwm/commit/37ebd67f5b242bb3c4f0acab5c7286dcd0f8ba4e , you should be able submit a pull request with the most recent models. That would complete request number one.

**Comment by kernol51** [comment]
OK - so did clean install of version 1.1.0 ... and can confirm it installs perfectly - but setting option 30 [XT12] to "Enable" reports "No Models Configured For Build" ?  

I the ran build for RT-A**C**86U [a model for which there is a Merlin 386.7-Alpha] and it worked for a while then failed;
[RT-AC86U-screen-grab](https://user-images.githubusercontent.com/50184416/171338020-f93471c7-b66a-4c6c-9cf8-246bd7a69272.JPG)

Then tried a GT=AX11000 [one of the new models] and it too started well - then failed in the same way.

Probable not a script issue ???  See enclosed pic and Error extraction from the build log of the RT-AC86U ...
[rt-ac86u-output.txt](https://github.com/Adamm00/amcfwm/files/8811475/rt-ac86u-output.txt)

**Comment by kernol51** [comment]
Not sure if you spotted this post - but I can't figure out how to update the automake - can you oblige?
[https://www.snbforums.com/threads/amcfwm-asuswrt-merlin-custom-firmware-manager.63227/post-763157](url)

This will explain why builds are not working for me ?

**Comment by kernol51** [comment]
> Not sure if you spotted this post - but I can't figure out how to update the automake - can you oblige? [https://www.snbforums.com/threads/amcfwm-asuswrt-merlin-custom-firmware-manager.63227/post-763157](url)
> 
> This will explain why builds are not working for me ?

thanks to Dave for sorting
